//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario_Alimentacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Salida
    {
        public long ID_Det_salid { get; set; }
        public long fk_Salida { get; set; }
        public int fk_TipoSalida { get; set; }
        public long fk_Producto { get; set; }
        public decimal Sal_Cantidad_Peso { get; set; }
        public string Sal_Observacion { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Salida Salida { get; set; }
        public virtual Tipo_Salida Tipo_Salida { get; set; }
    }
}
