//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario_Alimentacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nom_Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nom_Producto()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int ID_NomProducto { get; set; }
        public Nullable<int> Subcategoria { get; set; }
        public string NomProducto { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<decimal> Punto_pedido { get; set; }
        public Nullable<bool> Prop_Adicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
