//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario_Alimentacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Temporal = new HashSet<Temporal>();
        }
    
        public Nullable<int> fk_TipoDocum { get; set; }
        public Nullable<int> fk_Ciudad { get; set; }
        public int Prov_Docum { get; set; }
        public string Prov_Nombre { get; set; }
        public Nullable<int> Prov_Telefono { get; set; }
        public Nullable<int> Prov_Celular { get; set; }
        public string Prov_Email { get; set; }
        public string Prov_Direccion { get; set; }
        public string Prov_Fax { get; set; }
        public string Prov_ActiEcono { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Tipo_Documento Tipo_Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temporal> Temporal { get; set; }
    }
}
