//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario_Alimentacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporal2
    {
        public long ID_Det_salid { get; set; }
        public Nullable<long> fk_Salida { get; set; }
        public Nullable<int> fk_TipoSalida { get; set; }
        public Nullable<long> fk_Producto { get; set; }
        public Nullable<decimal> Sal_Cantidad_Peso { get; set; }
        public string Sal_Observacion { get; set; }
        public Nullable<int> ID_Categoria { get; set; }
        public Nullable<int> ID_Subcategoria { get; set; }
        public Nullable<int> ID_NomProducto { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Salida Salida { get; set; }
        public virtual Tipo_Salida Tipo_Salida { get; set; }
    }
}
