//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario_Alimentacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Usu_Nombre { get; set; }
        public string Usu_Contraseña { get; set; }
        public Nullable<int> Usu_Activo { get; set; }
        public Nullable<int> ID_Empleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
